version: '3'
services:
  app1:
    build: ./versionproduccion
    networks:
      redpr:
        aliases:
          - app1
    ports:
      - "8989:8989"
  app2:
    build: ./versionlatest
    networks:
      redpr:
        aliases:
          - app2
    ports:
      - "8686:8989"
networks:
  redpr:
